load("@rules_go//go:def.bzl", "go_library", "go_test")

go_library(
    name = "drive",
    srcs = ["drive.go"],
    importpath = "github.com/filmil/upspin-gdrive/cloud/storage/drive",
    visibility = ["//visibility:public"],
    deps = [
        "//config",
        "@io_upspin//cache",
        "@io_upspin//cloud/storage",
        "@io_upspin//errors",
        "@io_upspin//upspin",
        "@org_golang_google_api//drive/v3:drive",
        "@org_golang_google_api//googleapi",
        "@org_golang_x_oauth2//:oauth2",
    ],
)

go_test(
    name = "drive_test",
    srcs = ["drive_e2e_test.go"],
    embed = [":drive"],
    deps = [
        "@io_upspin//cloud/storage",
        "@io_upspin//errors",
        "@io_upspin//log",
    ],
)
